[package]
name = "benchy"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.10"
clap = { version = "4.5", features = ["derive"] }
tempfile = "3.10"
rand = "0.9.2"
num_cpus = "1.17"
libc= "0.2.179"